name = "StringViews"
uuid = "354b36f9-a18e-4713-926e-db85100087ba"
authors = ["Steven G. Johnson <stevenj@alum.mit.edu>"]
version = "1.3.1"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
